### PR TITLE
Fill mode fleshed out

### PR DESCRIPTION
**Pull request by somesmart**
Did some work to flesh out the fill mode from issue #15 - There might be a better way to do this, but it was working for me. This also includes pulling in the identifier (ISBN 10, 13, and LCCN) from Open Library which will help with issue #13 as well.

I added a display_unknowns function to the book class, which will show what's missing when you do a search. it might not be necessary forever, but it was useful in debugging this at least!

### CODE REVIEW

**Comment by chrrrisw** [comment]
Thanks for that, looking like a good start - I'm not sure that the logic in find_book is quite right, though. My head hurts too much at the moment to think it through properly, so I'll take a look at it again when I'm feeling better.
Thanks again, Chris.

**Comment by chrrrisw** [comment]
Thanks again. We'll need to modify the searchers, I think, to take the fill mode into account. They probably just overwrite what's there at the moment, even if it's a valid value. There's also the issue that isbnsearch.org returns a title of "ISBN XXX" when no valid data exists, so we might want to treat this as an unknown also.
Regards, Chris.

**Comment by somesmart** [comment]
What are you thinking for passing the fill back into the searchers? Should we allow the searcher to gather the data, and then evaluate the fields stored in book for unknowns and update them from the newly gathered data? I can play around with that idea if you think it's worthwhile. If not let me know what you think would be a better approach.

**Comment by chrrrisw** [comment]
Not sure at the moment.  I'm wondering if it's neater to return a dictionary from the searchers rather than a book, and have the book responsible for updating missing fields, rather than duplicate the logic in each searcher.

**Pull request merged**
