### PR TITLE
allow title to be entered if unknown

### PR DESCRIPTION
**Pull request by somesmart**
Here's just a quick update as a potential solution to allowing the user to enter the Title if we can't find it on the searched sites.

### CODE REVIEW

**Comment by chrrrisw** [comment]
Thanks again, good addition.
My initial comment would be that I'd rather not have the ```input``` in the Book class, as that is also used by the GTK interface and it would be weird having to input the title in this way when you have a graphical user interface. A better solution would be to check in the main text input loop after all searchers have been called and ask for the title if it remains unknown.
Regards,
Chris.

**Comment by chrrrisw** [comment]
I'll merge anyway, because I have some changes that will conflict - I'll fix it my side.
Thanks.

**Comment by somesmart** [comment]
Thanks, sorry I didn't get a chance to fix it before now!

**Comment by chrrrisw** [comment]
That's OK - I don't know what time zone you're in - so I assumed it was night where you are. It was a trivial change anyway and the merge went without a hitch.

**Pull request merged**
